### ISSUE TITLE
Set value programaticaly and reflect changes?

### ISSUE THREAD

**Issue by webdev23** [andrepxx/pure-knob#1]
Hi and thanks for your nice plug-in.

Found no way to easily set a new value from script, and reflect the changes with the adequate rotary action.

Currently what I do is replacing a knob by a new one with a new value, it works but this leads to some issues with event listeners, the goal would be to set many values on different knobs in the same time.

So far, I am setting the values as follow, changing at events. . Each knob div have an id. My script retrieve this data-values, so I can change it from there, and it has effect, but of course knobs don't follow on this case.

![screenshot at 2018-06-04 22 30 54](https://user-images.githubusercontent.com/2503337/40940167-3bb19eee-6847-11e8-8f1f-e1a52a06f603.png)

Currently building a simple audio workstation:

![gif1528143151_optimized](https://user-images.githubusercontent.com/2503337/40939315-93aaa076-6844-11e8-9df0-8cc554e42298.gif)

Also, the mouse wheel action is reversed, up wheel go down value?

Otherwise all good, no lags, simple and precise, thanks again.

**Comment by andrepxx** [comment]
Hey!

I'm glad you are enjoying the UI element.

Regarding your first issue.

If you have the knob object as returned by the `pureknob.createKnob(...)` method (not the DOM element), you should be able to change its value by calling the `.setValue(...)` method on it with the new value as the only parameter passed to the method.

If you use *JQuery*, you may associate the knob object itself with a DOM node using a construction like `$(someDOMNode).data('obj', knob);`, if `knob` is the knob object as returned by `pureknob.createKnob(...)`. Then, as soon as you have the DOM node at hand, you can retrieve the `knob` object itself again using `var knob = $(someDOMNode).data('obj');`.

(Note that, within the event handler that is triggered by the `knob`, you get the `knob` object passed as the first parameter anyways, so that you don't have to retrieve it by any other means in there.)

I also use the knob element in a (currently unpublished) audio application I develop, which is also why I incepted the control in the first place. This application contains, among other things, a chromatic tuner you can use to tune instruments. For this tuner, I use *pure-knob* in *needle mode* to display the deviation from the desired pitch in cents. (One cent is 1 / 1200 of an octave.) Of course, this value needs to get updated regularly as the user tunes the instrument. The code that updates the value (and therefore moves the tuner's "needle") is basically as follows.

	var centsDiv = $('.tunercentsknob').get(0); /* This is the DOM element. */
	var centsKnob = $(centsDiv).data('knob'); /* This is the knob object. */
	centsKnob.setValue(cents); /* This updates the knob's value and redraws it without recreating the object or DOM nodes. */

For me, this successfully updates the value and redraws the knob element without recreating it.

(Of course, for this to work, I had to associate the knob object with the DOM object like `$(centsDiv).data('knob', knob);` upon creation. This is bookkeeping, you have to do inside your application.)

However, keep in mind that, when you call `setValue(...)`, this will also notify all registered event listeners about the new value. Usually, this is fine, but you have to be aware of it. For example, you may never change the value from within the event listener, as this leads to infinite recursion. (Event listener changes value --> value change triggers event --> event listener changes value --> ... et cetera ad infinitum - or rather until the scripting engine runs out of stack and crashes.)

Regarding your second issue.

Yes. "Usually", when you spin the mouse wheel *up*, the value will *decrease*, if you spin it *down*, the value will *increase*. This is probably due to a rather arbitrary choice I made. :-) I designed this UI element because I needed it for an audio application as well - albeit a rather different one than yours - and at least in this particular application, scrolling *upwards* to turn the knob *counter-clockwise*, thereby *decreasing* the value (e. g. make a sound quieter if it acts as a level control), feels natural *for me*.

In case you want to change this behaviour, replace the following line ...

	var direction = delta > 0 ? 1 : (delta < 0 ? -1 : 0);

... (currently Line 512 of *pureknob.js*) with this ...

	var direction = delta > 0 ? -1 : (delta < 0 ? 1 : 0);

(I might add an option so that the invoking code can configure each knob to behave either one way or the other.)

However, keep in mind that the direction of the scroll wheel operation will depend on whether the operating system or window manager uses "natural scrolling" (which means: scrolling documents downwards when the mouse wheel moves upwards) or not. For example, if I enable "natural scrolling" in *GNOME 3 preferences*, this inverts the scroll behaviour of the knob. This is because the sign bit on the scroll event itself will also be inverted. I don't know how to determine the direction in which the scroll wheel is spinning other than from the sign of this event value, so this is the only clue I have. Therefore, keep in mind that the knob might behave inconsistently when the user changes system preferences like these and/or when moving between different systems and/or input devices, which have different default preferences for this. For example, I am pretty certain that *macOS*, by default, has "inverted" scroll behaviour - compared to the default settings of both *Windows* and most window managers for *Linux*.

Last but not least, the scroll wheel behaviour is also consistent with *JQuery knob*, which *pure-knob* was originally intended to replace.

Thanks a lot for your feedback.

Should you have more questions, suggestions, corrections or comments, or feel the need to clarify your issue, feel free to post a follow-up comment.

Regards.

**Comment by webdev23** [comment]
Thanks for your very detailed answer, we can feel the passion in it!

I took time to check the best solution for my use case. 
What I do is generating knobs in loops, to get the idea: 

```
function newknob(target,defval,newid,minval,maxval){
  var pureknob = new PureKnob()
  var wk = (window.innerWidth / 16.04) 
  var knob = pureknob.createKnob(wk, wk)
(...)

```
Then I generate them in bunch: 
```
for(var i=0;i<64;i++){
  newknob("panel",432,null,0,2550)
}
```
This means the constructor is not accessible this way, as it is overwritten at each loops.
Not using jquery, but complete native js/web audio api.

Finally it works great like this, with some calibration. It looks like our browser are enjoying very much canvas! Generating 64 of them doesn't disrupt my timing loops. 

Since the last day, this is how it has evolved. 
This is a little off the topic, but I think you should appreciate to see your knobs in action ;)

https://ponyhacks.com/dev/sequencer/Seq_demo01.mp4

**Comment by andrepxx** [comment]
First, please don't do this.

`var pureknob = new PureKnob();`

The "class" `PureKnob` implements a factory, which creates knobs. As soon as the JavaScript file is included, an instance of the factory is created and stored within the global variable `pureknob`. There is no need to create another factory, as the knobs that one factory produces will be the same as the ones that the other factory produces so you will only ever need a single factory in your entire application and it is already instantiated for you. Creating a new factory for each knob will just keep the runtime and garbage collector busier.

Second, why don't you just put your 64 knobs in a (possibly "global") array when your application starts?

```
function newknob(target, defval, newid, minval, maxval) {
   var wk = (window.innerWidth / 16.04);
   var knob = pureknob.createKnob(wk, wk);
(...)
   return knob;
}

(...)

var gridOfKnobs = [];

for (var i = 0; i < 64; i++) {
   var knob = newknob('panel', 432, null, 0, 2550);
   gridOfKnobs.push(knob);
}
```

Well, I don't know in which order you generate them, but say you generate them in column-major order, which means you start at the upper left corner, then go down, creating four knobs in a column, then start at the next column at the top, until you have 16 columns (4 * 16 = 64 knobs in total). This is also the order in which you append (`push(...)`) them to the `gridOfKnobs` array.

Now, let's say you want to change the value of knob at row 2 (so the third from the top, since indices are zero-based), column 3 (so the fourth from the left) and change its value to (say) 1337, so you calculate ...

```
var val = 1337;
var numRows = 4;
var numColumns = 16; /* We actually don't even need to know this. ;-) */
var rowId = 2;
var columnId = 3;
var idx = (columnId * numRows) + rowId; // 14
var knob = gridOfKnobs[idx];
knob.setValue(val);
```

Of course, you can also do all of that with dynamic values instead of these fixed integer literals. ;-)

You should think about the way you actually lay out your data structures. You will probably have your song structure stored somewhere, so I would write a function, which loads the current pattern from that structure and then updates all the knobs in the grid in a loop. Invoke this function each time you cross a pattern boundary and therefore move on to the next "page". As your grid is fixed, just keep the same knobs around all the time and keep that grid somewhere "global". (It doesn't have to be truly global. It just has to be visible to the function that updates the knobs.)

I am certain that it will be possible for you to keep the knob objects around. If you carefully lay out your data structures, it will probably become obvious where to store the knob objects, and your code will probably be much cleaner and your application will probably be much more extensible in the end.

**Comment by webdev23** [comment]
Yes i am storing the whole values in an array, and reading from there. 

I am not regenerating the whole knob sets at each value changes, as I am storing the values at events. The whole knob sets is regenerated in sequences (next pattern)
```

function repanel(storekey){
  var storekey = JSON.parse(localStorage.getItem(storekey))
  if (storekey !== null){
    // the only way I found to destruct all events listeners
    document.querySelectorAll("#panel .knobclass").forEach(function(e){
      e.outerHTML = ""
    })
    // Looping again, can't use the first loop. It collide
    for(var j=0;j<64;j++){
      newknob("panel", storekey[j], "knob"+j, 0 ,2550)
    }
  }
}
```

I know it is a bit, or maybe or complete bad idea! This is the origin of my question. 

Will figure out carefully what you explained. I can set a new knob (i mean creating/replacing) individually by passing his id in my function. It works, but it also create a small jump in my panel.

In all cases, thanks for your patience. I am fully self taught, now at a good level. But sometime i miss some basics. 

The bottom part of your message describe pretty much what I am doing, so I am happy with that.

I am glad to show you my work in construction: https://ponyhacks.com/dev/sequencer/sequencer.html 

But this isn't a request to help me on this, no worries. Glad to share.

**Comment by andrepxx** [comment]
I consider this issue resolved.
